-- CreateEnum
CREATE TYPE "RoleState" AS ENUM ('GURU', 'SISWA');

-- CreateTable
CREATE TABLE "TABLE_ROLE" (
    "id" UUID NOT NULL,
    "description" VARCHAR NOT NULL,

    CONSTRAINT "TABLE_ROLE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_CLASS" (
    "id" UUID NOT NULL,
    "title" VARCHAR NOT NULL,
    "waliKelas" VARCHAR NOT NULL,
    "countTotal" INTEGER NOT NULL,

    CONSTRAINT "TABLE_CLASS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_USER" (
    "id" UUID NOT NULL,
    "idRole" UUID NOT NULL,
    "fullName" VARCHAR NOT NULL,
    "uCredentials" VARCHAR NOT NULL,
    "uPassword" VARCHAR NOT NULL,

    CONSTRAINT "TABLE_USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_CLASS_ASSIGN" (
    "id" UUID NOT NULL,
    "idUser" UUID NOT NULL,
    "idClass" UUID NOT NULL,
    "state" "RoleState" NOT NULL,

    CONSTRAINT "TABLE_CLASS_ASSIGN_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_TOPIC" (
    "id" UUID NOT NULL,
    "idClass" UUID NOT NULL,
    "title" VARCHAR NOT NULL,
    "subject" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL,

    CONSTRAINT "TABLE_TOPIC_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_TEST" (
    "id" UUID NOT NULL,
    "idTopic" UUID NOT NULL,
    "title" VARCHAR NOT NULL,
    "question" TEXT NOT NULL,
    "expOutput" VARCHAR NOT NULL,
    "maxTries" INTEGER NOT NULL,

    CONSTRAINT "TABLE_TEST_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_HINT" (
    "id" UUID NOT NULL,
    "idTest" UUID NOT NULL,
    "hint1" TEXT NOT NULL,
    "hint2" TEXT NOT NULL,
    "hint3" TEXT NOT NULL,

    CONSTRAINT "TABLE_HINT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_SCORE" (
    "id" UUID NOT NULL,
    "idTest" UUID NOT NULL,
    "idUser" UUID NOT NULL,
    "level" VARCHAR NOT NULL,
    "averageScore" INTEGER NOT NULL,
    "flagOverride" BOOLEAN NOT NULL,
    "aiScore" TEXT NOT NULL,
    "aiSuggestion" TEXT NOT NULL,
    "aiFinishTime" TEXT NOT NULL,
    "uCode" TEXT NOT NULL,
    "overrideBy" UUID,
    "teacherScore" TEXT,
    "teacherSuggestion" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "TABLE_SCORE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TABLE_PROGRESS" (
    "idUser" UUID NOT NULL,
    "idTopic" UUID NOT NULL,
    "maxCount" INTEGER NOT NULL,
    "progressCount" INTEGER NOT NULL,

    CONSTRAINT "TABLE_PROGRESS_pkey" PRIMARY KEY ("idUser","idTopic")
);

-- AddForeignKey
ALTER TABLE "TABLE_USER" ADD CONSTRAINT "TABLE_USER_idRole_fkey" FOREIGN KEY ("idRole") REFERENCES "TABLE_ROLE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_CLASS_ASSIGN" ADD CONSTRAINT "TABLE_CLASS_ASSIGN_idUser_fkey" FOREIGN KEY ("idUser") REFERENCES "TABLE_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_CLASS_ASSIGN" ADD CONSTRAINT "TABLE_CLASS_ASSIGN_idClass_fkey" FOREIGN KEY ("idClass") REFERENCES "TABLE_CLASS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_TOPIC" ADD CONSTRAINT "TABLE_TOPIC_idClass_fkey" FOREIGN KEY ("idClass") REFERENCES "TABLE_CLASS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_TEST" ADD CONSTRAINT "TABLE_TEST_idTopic_fkey" FOREIGN KEY ("idTopic") REFERENCES "TABLE_TOPIC"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_HINT" ADD CONSTRAINT "TABLE_HINT_idTest_fkey" FOREIGN KEY ("idTest") REFERENCES "TABLE_TEST"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_SCORE" ADD CONSTRAINT "TABLE_SCORE_idTest_fkey" FOREIGN KEY ("idTest") REFERENCES "TABLE_TEST"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_SCORE" ADD CONSTRAINT "TABLE_SCORE_idUser_fkey" FOREIGN KEY ("idUser") REFERENCES "TABLE_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_SCORE" ADD CONSTRAINT "TABLE_SCORE_overrideBy_fkey" FOREIGN KEY ("overrideBy") REFERENCES "TABLE_USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_PROGRESS" ADD CONSTRAINT "TABLE_PROGRESS_idUser_fkey" FOREIGN KEY ("idUser") REFERENCES "TABLE_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TABLE_PROGRESS" ADD CONSTRAINT "TABLE_PROGRESS_idTopic_fkey" FOREIGN KEY ("idTopic") REFERENCES "TABLE_TOPIC"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
